services:
  open-webui:
    image: node:22-alpine3.20
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY:-H7-buoZ75tANPaTzbbM6jpK4IJEQpIZ5HY3C4n5Hty4=}
      - WEBUI_JWT_SECRET_KEY=${WEBUI_JWT_SECRET_KEY:-H7-buoZ75tANPaTzbbM6jpK4IJEQpIZ5HY3C4n5Hty4=}
      - WEBUI_NAME=${WEBUI_NAME:-Sauron AI}
      - WEBUI_DESCRIPTION=${WEBUI_DESCRIPTION:-Advanced AI Assistant}
      - OPENWEBUI_STREAM=false
    volumes:
    - .:/app
    working_dir: /app
    command: npm run dev
    expose:
      - "5173"
    networks:
      - app-network
  
  backend:
    image: python:3.11-slim-bookworm
    environment:
      - OPENWEBUI_STREAM=false
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - UVICORN_WORKERS=5
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY:-H7-buoZ75tANPaTzbbM6jpK4IJEQpIZ5HY3C4n5Hty4=}
      - WEBUI_JWT_SECRET_KEY=${WEBUI_JWT_SECRET_KEY:-H7-buoZ75tANPaTzbbM6jpK4IJEQpIZ5HY3C4n5Hty4=}
      - WEBUI_NAME=${WEBUI_NAME:-Sauron AI}
      - WEBUI_DESCRIPTION=${WEBUI_DESCRIPTION:-Advanced AI Assistant}
    volumes:
    - ./backend:/app
    working_dir: /app
    command: bash start.sh
    expose:
      - "8080"
    networks:
      - app-network
  
  nginx:
    image: nginx:latest
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
    - 8080:80
    depends_on:
      - open-webui
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge